#!/sbin/runscript
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

depend() {
	need net
}

start() {
	ebegin "Starting Erlang Port Mapper Daemon"
	start-stop-daemon --start --quiet --user nobody --group nobody --exec /usr/bin/epmd -- -daemon
	eend $?
}

stop() {
	ebegin "Stopping Erlang Port Mapper Daemon"
	/usr/bin/epmd -kill >/dev/null
	eend $?
}
