#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-lang/erlang/files/epmd.init,v 1.1 2010/11/08 00:47:30 fauli Exp $

depend() {
	need net
}

start() {
	ebegin "Starting Erlang Port Mapper Daemon"
	start-stop-daemon --start --quiet --user nobody --group nobody --exec /usr/bin/epmd -- -daemon
	eend $?
}

stop() {
	ebegin "Stopping Erlang Port Mapper Daemon"
	/usr/bin/epmd -kill >/dev/null
	eend $?
}
