# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DOCS_BUILDER="doxygen"
DOCS_DIR="docs/doxygen"
DOCS_DEPEND="media-gfx/graphviz"
# Tracks the ROCm 10.0 cohort's LLVM slot; the stack is subslot-pinned as a
# single dependency closure, so all of it must use one LLVM major.
LLVM_COMPAT=( 23 )
ROCM_VERSION=${PV}

inherit cmake docs edo flag-o-matic llvm-r2 multiprocessing rocm

DESCRIPTION="AMD's library for BLAS on ROCm"
HOMEPAGE="https://github.com/ROCm/rocm-libraries/tree/develop/projects/rocblas"

if [[ "${PV}" == 9999 ]] ; then
	inherit git-r3
	EGIT_REPO_URI="https://github.com/ROCm/rocm-libraries.git"
	EGIT_BRANCH="develop"
	S="${WORKDIR}/${P}/projects/rocblas"
	SLOT="0/9999"
	SLOT_NOLIVE="0/10.0"
else
	# AMD retired the rocm-* release line at rocm-7.2.4 (2026-05-28); the same
	# per-component assets ship under therock-<major.minor> tags now.
	SRC_URI="https://github.com/ROCm/rocm-libraries/releases/download/therock-$(ver_cut 1-2)/rocblas.tar.gz -> rocblas-${PV}.tar.gz"
	S="${WORKDIR}/rocblas"
	SLOT="0/$(ver_cut 1-2)"
	SLOT_NOLIVE=${SLOT}
	KEYWORDS="~amd64"
fi

LICENSE="MIT BSD"
IUSE="benchmark hipblaslt roctracer test"
RESTRICT="!test? ( test )"
REQUIRED_USE="${ROCM_REQUIRED_USE}"

# dev-util/hipcc[amd-llvm] is a build requirement, not documentation.
# rocm_use_clang() resolves the compiler via `hipconfig --hipclangpath`, and
# hipcc points that at llvm-core/rocm-llvm only when the flag is set. This
# package cannot be compiled by a vanilla LLVM: Tensile GENERATES gfx1150
# assembly the vanilla assembler rejects ("operands are not valid for this GPU
# or mode" on v_cvt_f16_f32), and being generated it cannot be patched away.
# Until now that requirement lived only in a profiles/package.mask comment, so
# building against a hipcc without the flag died deep in compilation with no
# resolver-level signal. hipconfig belongs to hipcc and was reached only
# transitively through dev-util/hip, which cannot carry the USE-dep.
#
# Unconditional deliberately. Every failure on record is a gfx11xx/gfx12xx one,
# so a narrower amdgpu_targets_*? form may well be correct -- but nobody has
# built this against a vanilla LLVM for a CDNA-only target, and claiming
# support that was never verified is the worse error. Narrow it once someone
# has that build. # verified 2026-08-30
BDEPEND="
	dev-build/rocm-cmake:${SLOT_NOLIVE}
	dev-util/hipcc:${SLOT_NOLIVE}[amd-llvm]
"

RDEPEND="
	dev-util/hip:${SLOT_NOLIVE}
	roctracer? ( dev-util/roctracer:${SLOT_NOLIVE} )
	hipblaslt? ( sci-libs/hipBLASLt:${SLOT_NOLIVE} )
	benchmark? (
		dev-cpp/gtest:=
		dev-util/rocm-smi:${SLOT_NOLIVE}
		llvm-runtimes/openmp
		sci-libs/flexiblas
	)
"

DEPEND="
	${RDEPEND}
	>=dev-cpp/msgpack-cxx-6.0.0
	test? (
		dev-cpp/gtest:=
		dev-util/rocm-smi:${SLOT_NOLIVE}
		llvm-runtimes/openmp
		sci-libs/flexiblas
	)
	dev-util/Tensile:${SLOT}
"

QA_FLAGS_IGNORED="/usr/lib64/rocblas/library/.*"

PATCHES=(
	# ${PN}-5.4.2-add-missing-header.patch dropped: clients/include/host_alloc.hpp
	# carries `#include <new>` upstream as of 10.0. verified 2026-08-30.
	"${FILESDIR}"/${PN}-10.0.0-expand-isa-compatibility.patch
	"${FILESDIR}"/${PN}-7.1.0-no-git.patch
)

src_prepare() {
	cmake_src_prepare

	# Remove RPATH's, fixes multilib compatibility
	# `sed` exits 0 on no-match, so a stale anchor here would silently leave the
	# client RPATHs in place instead of short-circuiting the function.
	grep -qF 'apply_omp_settings' clients/CMakeLists.txt ||
		die 'apply_omp_settings anchor moved in clients/CMakeLists.txt'
	sed -e "/apply_omp_settings/a return()" -i clients/CMakeLists.txt || die

	# Disable automagic linking with roctracer
	# `sed` exits 0 on no-match: a stale anchor would silently restore the
	# automagic dependency, linking roctracer whenever it happens to be installed.
	grep -qF 'if(ROCTRACER_INCLUDE_DIR' library/CMakeLists.txt ||
		die 'ROCTRACER_INCLUDE_DIR anchor moved in library/CMakeLists.txt'
	sed -e "s/if(ROCTRACER_INCLUDE_DIR/if(ROCBLAS_ENABLE_MARKER AND ROCTRACER_INCLUDE_DIR/" \
		-i library/CMakeLists.txt || die
}

src_configure() {
	llvm_prepend_path "${LLVM_SLOT}"
	rocm_use_clang

	# Tensile takes only --cxx-compiler from CMake (Tensile_COMPILER); its
	# assembler, C compiler and offload bundler default to BARE NAMES resolved
	# through PATH (Tensile/Utilities/Toolchain.py, ToolchainDefaults).
	# llvm_prepend_path just put the vanilla LLVM slot at the front, so without
	# this the gfx kernels are GENERATED by the clang++ rocm_use_clang picked and
	# then ASSEMBLED by a different one. With hipcc[amd-llvm] that split is fatal:
	# vanilla clang rejects the assembly AMD's Tensile emits for gfx1150
	# ("operands are not valid for this GPU or mode" on v_cvt_f16_f32).
	# A no-op when hipcc points at the system LLVM. verified 2026-08-30.
	export PATH="${CXX%/*}:${PATH}"

	# too many warnings
	append-cxxflags -Wno-explicit-specialization-storage-class -Wno-unused-value

	local mycmakeargs=(
		-DCMAKE_SKIP_RPATH=ON
		-DROCM_SYMLINK_LIBS=OFF
		-DAMDGPU_TARGETS="$(get_amdgpu_flags)"
		-DBUILD_WITH_TENSILE=ON
		-DCMAKE_INSTALL_INCLUDEDIR="include/rocblas"
		-DBUILD_CLIENTS_SAMPLES=OFF
		-DBUILD_CLIENTS_TESTS="$(usex test ON OFF)"
		-DBUILD_CLIENTS_BENCHMARKS="$(usex benchmark ON OFF)"
		-DBUILD_WITH_PIP=OFF
		-DBUILD_WITH_HIPBLASLT="$(usex hipblaslt ON OFF)"
		-DROCBLAS_ENABLE_MARKER="$(usex roctracer ON OFF)"
		-DLINK_BLIS=OFF
		-DTensile_COMPILER="${CXX}"
		-DTensile_ROOT="${EPREFIX}/usr/share/Tensile"
		-DTensile_CPU_THREADS="$(makeopts_jobs)"
		-Wno-dev
	)

	if use benchmark || use test; then
		mycmakeargs+=(
			-DBLA_PREFER_PKGCONFIG=ON
			-DBLA_PKGCONFIG_BLAS=flexiblas
			-DBLA_VENDOR=FlexiBLAS
		)
	fi

	cmake_src_configure
}

src_compile() {
	docs_compile
	cmake_src_compile
}

src_test() {
	check_amdgpu
	cd "${BUILD_DIR}"/clients/staging || die
	export ROCBLAS_TEST_TIMEOUT=3600 ROCBLAS_TENSILE_LIBPATH="${BUILD_DIR}/Tensile/library"
	export LD_LIBRARY_PATH="${BUILD_DIR}/clients:${BUILD_DIR}/library/src"

	# `--gtest_filter=*quick*:*pre_checkin*-*known_bug*` is >1h on 7900XTX
	edob ./rocblas-test --yaml rocblas_smoke.yaml
}

src_install() {
	cmake_src_install

	if use benchmark; then
		cd "${BUILD_DIR}" || die
		dolib.a clients/librocblas_fortran_client.a
		dobin clients/staging/rocblas-bench
	fi

	# Stop llvm-strip from removing .strtab section from *.hsaco files,
	# otherwise rocclr/elf/elf.cpp complains with "failed: null sections(STRTAB)" and crashes
	dostrip -x "/usr/$(get_libdir)/rocblas/library/"
}
