# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DISTUTILS_USE_PEP517=pdm-backend
PYTHON_COMPAT=( python3_{11..14} )

inherit distutils-r1 pypi

DESCRIPTION="Parse partial JSON generated by LLM"
HOMEPAGE="
	https://promplate.dev/partial-json-parser
	https://github.com/promplate/partial-json-parser
	https://pypi.org/project/partial-json-parser/
"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"

# No required runtime deps; the only optional extra is `playground` which
# pulls dev-python/rich and ships the json-playground console script.
# Enable that extra by default — the binary is otherwise broken.
RDEPEND="
	dev-python/rich[${PYTHON_USEDEP}]
"
